# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [20]:
# Method 2
a = np.random.rand(2,3,5)

In [ ]:
# Method 3

#### 4. Print *a*.


In [4]:
# your code here
print(a)

[[[0.23310745 0.43837455 0.06884156 0.23577269 0.24508083]
  [0.20334981 0.09298056 0.53264997 0.50023613 0.9817101 ]
  [0.5851892  0.56683193 0.92446289 0.33377199 0.77766645]]

 [[0.9264229  0.46688503 0.49389298 0.79750086 0.43588516]
  [0.05727997 0.01141643 0.18212192 0.46741021 0.61384359]
  [0.34101282 0.77902538 0.46722123 0.38485604 0.91053903]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [6]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here
print(a.size)
print(b.size)

#yes, a and b have the same size

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here
a_b = np.add(a,b)

# it is not possible because the shape of a and b is not equal

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = np.add(a,c)
print(d)

# now it is working because both have the same shape

[[[1.23310745 1.43837455 1.06884156 1.23577269 1.24508083]
  [1.20334981 1.09298056 1.53264997 1.50023613 1.9817101 ]
  [1.5851892  1.56683193 1.92446289 1.33377199 1.77766645]]

 [[1.9264229  1.46688503 1.49389298 1.79750086 1.43588516]
  [1.05727997 1.01141643 1.18212192 1.46741021 1.61384359]
  [1.34101282 1.77902538 1.46722123 1.38485604 1.91053903]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
# your code/answer here
print(a)
print(d)

#values are different because d is the sum of a and c

[[[0.23310745 0.43837455 0.06884156 0.23577269 0.24508083]
  [0.20334981 0.09298056 0.53264997 0.50023613 0.9817101 ]
  [0.5851892  0.56683193 0.92446289 0.33377199 0.77766645]]

 [[0.9264229  0.46688503 0.49389298 0.79750086 0.43588516]
  [0.05727997 0.01141643 0.18212192 0.46741021 0.61384359]
  [0.34101282 0.77902538 0.46722123 0.38485604 0.91053903]]]
[[[1.23310745 1.43837455 1.06884156 1.23577269 1.24508083]
  [1.20334981 1.09298056 1.53264997 1.50023613 1.9817101 ]
  [1.5851892  1.56683193 1.92446289 1.33377199 1.77766645]]

 [[1.9264229  1.46688503 1.49389298 1.79750086 1.43588516]
  [1.05727997 1.01141643 1.18212192 1.46741021 1.61384359]
  [1.34101282 1.77902538 1.46722123 1.38485604 1.91053903]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.23310745 0.43837455 0.06884156 0.23577269 0.24508083]
  [0.20334981 0.09298056 0.53264997 0.50023613 0.9817101 ]
  [0.5851892  0.56683193 0.92446289 0.33377199 0.77766645]]

 [[0.9264229  0.46688503 0.49389298 0.79750086 0.43588516]
  [0.05727997 0.01141643 0.18212192 0.46741021 0.61384359]
  [0.34101282 0.77902538 0.46722123 0.38485604 0.91053903]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here
print(a)
print(e)

# yes, they are equal. i think it's because of their dimentional shape. But I'm not sure

[[[0.23310745 0.43837455 0.06884156 0.23577269 0.24508083]
  [0.20334981 0.09298056 0.53264997 0.50023613 0.9817101 ]
  [0.5851892  0.56683193 0.92446289 0.33377199 0.77766645]]

 [[0.9264229  0.46688503 0.49389298 0.79750086 0.43588516]
  [0.05727997 0.01141643 0.18212192 0.46741021 0.61384359]
  [0.34101282 0.77902538 0.46722123 0.38485604 0.91053903]]]
[[[0.23310745 0.43837455 0.06884156 0.23577269 0.24508083]
  [0.20334981 0.09298056 0.53264997 0.50023613 0.9817101 ]
  [0.5851892  0.56683193 0.92446289 0.33377199 0.77766645]]

 [[0.9264229  0.46688503 0.49389298 0.79750086 0.43588516]
  [0.05727997 0.01141643 0.18212192 0.46741021 0.61384359]
  [0.34101282 0.77902538 0.46722123 0.38485604 0.91053903]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [23]:
# your code here
d_max = np.max(d)
d_max

1.9817101039719955

In [24]:
d_min = np.min(d)
d_min

1.0114164298154051

In [25]:
d_mean = np.mean(d)
d_mean

1.4685113223518338

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [36]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [34]:
# your code here
print(d)
print(f)

[[[1.23310745 1.43837455 1.06884156 1.23577269 1.24508083]
  [1.20334981 1.09298056 1.53264997 1.50023613 1.9817101 ]
  [1.5851892  1.56683193 1.92446289 1.33377199 1.77766645]]

 [[1.9264229  1.46688503 1.49389298 1.79750086 1.43588516]
  [1.05727997 1.01141643 1.18212192 1.46741021 1.61384359]
  [1.34101282 1.77902538 1.46722123 1.38485604 1.91053903]]]
[[[ 25.  25.  25.  25.  25.]
  [ 25.  25.  75.  75. 100.]
  [ 75.  75.  75.  25.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.   0.  25.  25.  75.]
  [ 25.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here